site_name: 神秘
site_url: https://tutor.xireiki.com
site_author: xireiki
copyright: Copyright &copy; 2024 - 2024 xireiki
repo_url: https://github.com/jasmoli/tutor
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/xiayinlily
    - icon: fontawesome/brands/github
      link: https://github.com/jasmoli/tutor
    - icon: simple/hexo
      link: https://xireiki.com
theme:
  name: material
  logo: assets/icon.gif
  favicon: assets/icon.gif
  features:
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - 主页: index.md
  - 介绍: introduction/index.md
  - 安装 Termux: termux/index.md
  - 安装神秘: mystery/index.md
  - 新手配置: novice/index.md
  - 神秘面板首页: home/index.md
  - 设置:
    - settings/index.md
    - 出站提供者: settings/outbound-provider/index.md
    - 出站: settings/outbound/index.md
    - DNS: settings/dns/index.md
    - 模块设置: settings/setting/index.md
    - 核心日志: settings/log/index.md
    - 内置 NTP: settings/ntp/index.md
  - 修改配置文件: config/index.md
  - 常见问题: FAQ/index.md
plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - build: true
          default: true
          locale: zh
          name: 简体中文
        - build: true
          default: false
          locale: en
          name: English
          nav_translations:
            主页: Home
            介绍: Introductions
            安装 Termux: Installing Termux
            安装神秘: Installing the 神秘 Module
            新手配置: Novice Configuration
            神秘面板首页: Mystery Panel Home
            设置: Settings

            出站提供者: Outbound Provider
            出站: Outbound
            DNS: DNS
            模块设置: Module Settings
            核心日志: Log
            内置 NTP: NTP

            修改配置文件: Modify the configuration file

            常见问题: FAQ
